// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/context.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Context struct {
	Custom               map[string]string `protobuf:"bytes,1,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Response             *Context_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Request              *Context_Request  `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	User                 *User             `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec82a4a6d16b0328, []int{0}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetCustom() map[string]string {
	if m != nil {
		return m.Custom
	}
	return nil
}

func (m *Context) GetResponse() *Context_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Context) GetRequest() *Context_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Context) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Context) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Context_Response struct {
	Finished             bool                      `protobuf:"varint,1,opt,name=finished,proto3" json:"finished,omitempty"`
	Headers              *Context_Response_Headers `protobuf:"bytes,2,opt,name=headers,proto3" json:"headers,omitempty"`
	HeadersSent          bool                      `protobuf:"varint,3,opt,name=headers_sent,proto3" json:"headers_sent,omitempty"`
	StatusCode           int32                     `protobuf:"varint,4,opt,name=status_code,proto3" json:"status_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Context_Response) Reset()         { *m = Context_Response{} }
func (m *Context_Response) String() string { return proto.CompactTextString(m) }
func (*Context_Response) ProtoMessage()    {}
func (*Context_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec82a4a6d16b0328, []int{0, 2}
}

func (m *Context_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context_Response.Unmarshal(m, b)
}
func (m *Context_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context_Response.Marshal(b, m, deterministic)
}
func (m *Context_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context_Response.Merge(m, src)
}
func (m *Context_Response) XXX_Size() int {
	return xxx_messageInfo_Context_Response.Size(m)
}
func (m *Context_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Context_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Context_Response proto.InternalMessageInfo

func (m *Context_Response) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

func (m *Context_Response) GetHeaders() *Context_Response_Headers {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Context_Response) GetHeadersSent() bool {
	if m != nil {
		return m.HeadersSent
	}
	return false
}

func (m *Context_Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

type Context_Response_Headers struct {
	ContentType          string   `protobuf:"bytes,1,opt,name=content_type,proto3" json:"content_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context_Response_Headers) Reset()         { *m = Context_Response_Headers{} }
func (m *Context_Response_Headers) String() string { return proto.CompactTextString(m) }
func (*Context_Response_Headers) ProtoMessage()    {}
func (*Context_Response_Headers) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec82a4a6d16b0328, []int{0, 2, 0}
}

func (m *Context_Response_Headers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context_Response_Headers.Unmarshal(m, b)
}
func (m *Context_Response_Headers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context_Response_Headers.Marshal(b, m, deterministic)
}
func (m *Context_Response_Headers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context_Response_Headers.Merge(m, src)
}
func (m *Context_Response_Headers) XXX_Size() int {
	return xxx_messageInfo_Context_Response_Headers.Size(m)
}
func (m *Context_Response_Headers) XXX_DiscardUnknown() {
	xxx_messageInfo_Context_Response_Headers.DiscardUnknown(m)
}

var xxx_messageInfo_Context_Response_Headers proto.InternalMessageInfo

func (m *Context_Response_Headers) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

type Context_Request struct {
	Body                 string                   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Env                  map[string]string        `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Headers              *Context_Request_Headers `protobuf:"bytes,3,opt,name=headers,proto3" json:"headers,omitempty"`
	HttpVersion          string                   `protobuf:"bytes,4,opt,name=http_version,proto3" json:"http_version,omitempty"`
	Method               string                   `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Socket               *Context_Request_Socket  `protobuf:"bytes,6,opt,name=socket,proto3" json:"socket,omitempty"`
	Url                  *Context_Request_Url     `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Cookies              map[string]string        `protobuf:"bytes,8,rep,name=cookies,proto3" json:"cookies,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Context_Request) Reset()         { *m = Context_Request{} }
func (m *Context_Request) String() string { return proto.CompactTextString(m) }
func (*Context_Request) ProtoMessage()    {}
func (*Context_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec82a4a6d16b0328, []int{0, 3}
}

func (m *Context_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context_Request.Unmarshal(m, b)
}
func (m *Context_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context_Request.Marshal(b, m, deterministic)
}
func (m *Context_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context_Request.Merge(m, src)
}
func (m *Context_Request) XXX_Size() int {
	return xxx_messageInfo_Context_Request.Size(m)
}
func (m *Context_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Context_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Context_Request proto.InternalMessageInfo

func (m *Context_Request) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Context_Request) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Context_Request) GetHeaders() *Context_Request_Headers {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Context_Request) GetHttpVersion() string {
	if m != nil {
		return m.HttpVersion
	}
	return ""
}

func (m *Context_Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Context_Request) GetSocket() *Context_Request_Socket {
	if m != nil {
		return m.Socket
	}
	return nil
}

func (m *Context_Request) GetUrl() *Context_Request_Url {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *Context_Request) GetCookies() map[string]string {
	if m != nil {
		return m.Cookies
	}
	return nil
}

type Context_Request_Socket struct {
	Encrypted            bool     `protobuf:"varint,1,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	RemoteAddress        string   `protobuf:"bytes,2,opt,name=remote_address,proto3" json:"remote_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context_Request_Socket) Reset()         { *m = Context_Request_Socket{} }
func (m *Context_Request_Socket) String() string { return proto.CompactTextString(m) }
func (*Context_Request_Socket) ProtoMessage()    {}
func (*Context_Request_Socket) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec82a4a6d16b0328, []int{0, 3, 2}
}

func (m *Context_Request_Socket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context_Request_Socket.Unmarshal(m, b)
}
func (m *Context_Request_Socket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context_Request_Socket.Marshal(b, m, deterministic)
}
func (m *Context_Request_Socket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context_Request_Socket.Merge(m, src)
}
func (m *Context_Request_Socket) XXX_Size() int {
	return xxx_messageInfo_Context_Request_Socket.Size(m)
}
func (m *Context_Request_Socket) XXX_DiscardUnknown() {
	xxx_messageInfo_Context_Request_Socket.DiscardUnknown(m)
}

var xxx_messageInfo_Context_Request_Socket proto.InternalMessageInfo

func (m *Context_Request_Socket) GetEncrypted() bool {
	if m != nil {
		return m.Encrypted
	}
	return false
}

func (m *Context_Request_Socket) GetRemoteAddress() string {
	if m != nil {
		return m.RemoteAddress
	}
	return ""
}

type Context_Request_Url struct {
	Raw                  string   `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Protocol             string   `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Full                 string   `protobuf:"bytes,3,opt,name=full,proto3" json:"full,omitempty"`
	Hostname             string   `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 string   `protobuf:"bytes,5,opt,name=port,proto3" json:"port,omitempty"`
	Pathname             string   `protobuf:"bytes,6,opt,name=pathname,proto3" json:"pathname,omitempty"`
	Search               string   `protobuf:"bytes,7,opt,name=search,proto3" json:"search,omitempty"`
	Hash                 string   `protobuf:"bytes,8,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context_Request_Url) Reset()         { *m = Context_Request_Url{} }
func (m *Context_Request_Url) String() string { return proto.CompactTextString(m) }
func (*Context_Request_Url) ProtoMessage()    {}
func (*Context_Request_Url) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec82a4a6d16b0328, []int{0, 3, 3}
}

func (m *Context_Request_Url) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context_Request_Url.Unmarshal(m, b)
}
func (m *Context_Request_Url) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context_Request_Url.Marshal(b, m, deterministic)
}
func (m *Context_Request_Url) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context_Request_Url.Merge(m, src)
}
func (m *Context_Request_Url) XXX_Size() int {
	return xxx_messageInfo_Context_Request_Url.Size(m)
}
func (m *Context_Request_Url) XXX_DiscardUnknown() {
	xxx_messageInfo_Context_Request_Url.DiscardUnknown(m)
}

var xxx_messageInfo_Context_Request_Url proto.InternalMessageInfo

func (m *Context_Request_Url) GetRaw() string {
	if m != nil {
		return m.Raw
	}
	return ""
}

func (m *Context_Request_Url) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Context_Request_Url) GetFull() string {
	if m != nil {
		return m.Full
	}
	return ""
}

func (m *Context_Request_Url) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Context_Request_Url) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Context_Request_Url) GetPathname() string {
	if m != nil {
		return m.Pathname
	}
	return ""
}

func (m *Context_Request_Url) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *Context_Request_Url) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Context_Request_Headers struct {
	ContentType          string   `protobuf:"bytes,1,opt,name=content_type,proto3" json:"content_type,omitempty"`
	Cookie               string   `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
	UserAgent            string   `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context_Request_Headers) Reset()         { *m = Context_Request_Headers{} }
func (m *Context_Request_Headers) String() string { return proto.CompactTextString(m) }
func (*Context_Request_Headers) ProtoMessage()    {}
func (*Context_Request_Headers) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec82a4a6d16b0328, []int{0, 3, 4}
}

func (m *Context_Request_Headers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context_Request_Headers.Unmarshal(m, b)
}
func (m *Context_Request_Headers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context_Request_Headers.Marshal(b, m, deterministic)
}
func (m *Context_Request_Headers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context_Request_Headers.Merge(m, src)
}
func (m *Context_Request_Headers) XXX_Size() int {
	return xxx_messageInfo_Context_Request_Headers.Size(m)
}
func (m *Context_Request_Headers) XXX_DiscardUnknown() {
	xxx_messageInfo_Context_Request_Headers.DiscardUnknown(m)
}

var xxx_messageInfo_Context_Request_Headers proto.InternalMessageInfo

func (m *Context_Request_Headers) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Context_Request_Headers) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

func (m *Context_Request_Headers) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func init() {
	proto.RegisterType((*Context)(nil), "protos.Context")
	proto.RegisterMapType((map[string]string)(nil), "protos.Context.CustomEntry")
	proto.RegisterMapType((map[string]string)(nil), "protos.Context.TagsEntry")
	proto.RegisterType((*Context_Response)(nil), "protos.Context.Response")
	proto.RegisterType((*Context_Response_Headers)(nil), "protos.Context.Response.Headers")
	proto.RegisterType((*Context_Request)(nil), "protos.Context.Request")
	proto.RegisterMapType((map[string]string)(nil), "protos.Context.Request.CookiesEntry")
	proto.RegisterMapType((map[string]string)(nil), "protos.Context.Request.EnvEntry")
	proto.RegisterType((*Context_Request_Socket)(nil), "protos.Context.Request.Socket")
	proto.RegisterType((*Context_Request_Url)(nil), "protos.Context.Request.Url")
	proto.RegisterType((*Context_Request_Headers)(nil), "protos.Context.Request.Headers")
}

func init() { proto.RegisterFile("protos/context.proto", fileDescriptor_ec82a4a6d16b0328) }

var fileDescriptor_ec82a4a6d16b0328 = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0x13, 0x3d,
	0x10, 0xd6, 0x36, 0xe9, 0x7e, 0x4c, 0xaa, 0x57, 0x2f, 0x56, 0x05, 0xcb, 0x96, 0x8f, 0x55, 0x85,
	0x50, 0x2e, 0x0d, 0xa2, 0x45, 0x85, 0xf6, 0x80, 0x84, 0xaa, 0x4a, 0x3d, 0x71, 0x30, 0xf4, 0x1c,
	0xb9, 0xbb, 0xd3, 0x6e, 0xd4, 0xcd, 0x3a, 0xd8, 0xde, 0x94, 0xfc, 0x1f, 0xfe, 0x07, 0x3f, 0x83,
	0x03, 0x7f, 0x06, 0x79, 0xec, 0x4d, 0x3f, 0x20, 0x87, 0xdc, 0xe6, 0xe3, 0x79, 0xc6, 0x9e, 0x67,
	0xc6, 0x86, 0xed, 0x99, 0x92, 0x46, 0xea, 0x37, 0x85, 0x6c, 0x0c, 0x7e, 0x37, 0x23, 0x72, 0x59,
	0xe8, 0xa2, 0xd9, 0x23, 0x9f, 0x6d, 0x35, 0x2a, 0x97, 0xda, 0xfd, 0x31, 0x80, 0xe8, 0xc4, 0x81,
	0xd9, 0x01, 0x84, 0x45, 0xab, 0x8d, 0x9c, 0xa6, 0x41, 0xde, 0x1b, 0x0e, 0xf6, 0x77, 0x1c, 0x46,
	0x8f, 0x3c, 0x60, 0x74, 0x42, 0xd9, 0xd3, 0xc6, 0xa8, 0x05, 0xf7, 0x50, 0xf6, 0x0e, 0x62, 0x85,
	0x7a, 0x26, 0x1b, 0x8d, 0xe9, 0x46, 0x1e, 0x0c, 0x07, 0xfb, 0xe9, 0x43, 0x1a, 0xf7, 0x79, 0xbe,
	0x44, 0xb2, 0xb7, 0x10, 0x29, 0xfc, 0xd6, 0xa2, 0x36, 0x69, 0x8f, 0x48, 0x4f, 0xfe, 0x26, 0x51,
	0x9a, 0x77, 0x38, 0xb6, 0x07, 0x7d, 0x23, 0xae, 0x74, 0xda, 0xa7, 0xbb, 0x3d, 0x7d, 0x88, 0xff,
	0x2a, 0xae, 0xb4, 0xbb, 0x19, 0xc1, 0x58, 0x0e, 0x7d, 0xdb, 0x66, 0xba, 0x49, 0xe5, 0xb7, 0x3a,
	0xf8, 0xb9, 0x46, 0xc5, 0x29, 0x93, 0x1d, 0xc1, 0xe0, 0x4e, 0x43, 0xec, 0x7f, 0xe8, 0x5d, 0xe3,
	0x22, 0x0d, 0xf2, 0x60, 0x98, 0x70, 0x6b, 0xb2, 0x6d, 0xd8, 0x9c, 0x8b, 0xba, 0x75, 0x7d, 0x25,
	0xdc, 0x39, 0xc7, 0x1b, 0x1f, 0x82, 0xec, 0x3d, 0x24, 0xcb, 0xf3, 0xd6, 0x22, 0xfe, 0x0a, 0x20,
	0xee, 0xe4, 0x60, 0x19, 0xc4, 0x97, 0x93, 0x66, 0xa2, 0x2b, 0x2c, 0x89, 0x1d, 0xf3, 0xa5, 0xcf,
	0x8e, 0x21, 0xaa, 0x50, 0x94, 0xa8, 0xb4, 0x57, 0x35, 0x5f, 0xa5, 0xea, 0xe8, 0xcc, 0xe1, 0x78,
	0x47, 0x60, 0xbb, 0xb0, 0xe5, 0xcd, 0xb1, 0xc6, 0xc6, 0x29, 0x1c, 0xf3, 0x7b, 0x31, 0x96, 0xc3,
	0x40, 0x1b, 0x61, 0x5a, 0x3d, 0x2e, 0x64, 0x89, 0x69, 0x3f, 0x0f, 0x86, 0x9b, 0xfc, 0x6e, 0x28,
	0xdb, 0x83, 0xe8, 0xec, 0xb6, 0x20, 0x2d, 0x54, 0x63, 0xc6, 0x66, 0x31, 0x43, 0xdf, 0xea, 0xbd,
	0x58, 0xf6, 0x3b, 0x84, 0xc8, 0xcf, 0x8c, 0x31, 0xe8, 0x5f, 0xc8, 0xb2, 0x93, 0x84, 0x6c, 0xb6,
	0x0f, 0x3d, 0x6c, 0xe6, 0xe9, 0x06, 0x4d, 0x2f, 0x5f, 0x31, 0xed, 0xd1, 0x69, 0x33, 0x77, 0x43,
	0xb4, 0x60, 0x76, 0x74, 0x2b, 0x82, 0xdb, 0x92, 0x97, 0xab, 0x78, 0xff, 0xd4, 0xc0, 0x98, 0xd9,
	0x78, 0x8e, 0x4a, 0x4f, 0x64, 0x43, 0x0d, 0x26, 0xfc, 0x5e, 0x8c, 0x3d, 0x86, 0x70, 0x8a, 0xa6,
	0x92, 0x25, 0x2d, 0x49, 0xc2, 0xbd, 0xc7, 0x0e, 0x21, 0xd4, 0xb2, 0xb8, 0x46, 0x93, 0x86, 0x74,
	0xea, 0x8b, 0x55, 0xa7, 0x7e, 0x21, 0x14, 0xf7, 0x68, 0xb6, 0x07, 0xbd, 0x56, 0xd5, 0x69, 0x44,
	0xa4, 0x9d, 0x55, 0xa4, 0x73, 0x55, 0x73, 0x8b, 0x63, 0x1f, 0x21, 0x2a, 0xa4, 0xbc, 0x9e, 0xa0,
	0x4e, 0x63, 0x52, 0xe5, 0xd5, 0x2a, 0xca, 0x89, 0x83, 0x39, 0x65, 0x3a, 0x52, 0x76, 0x08, 0x71,
	0x27, 0xd7, 0x5a, 0x3b, 0x78, 0x0c, 0x5b, 0x77, 0x0b, 0xae, 0xc5, 0xfd, 0x0c, 0xa1, 0x6b, 0x9a,
	0x3d, 0x83, 0x04, 0x9b, 0x42, 0x2d, 0x66, 0x66, 0xb9, 0xbd, 0xb7, 0x01, 0xf6, 0x1a, 0xfe, 0x53,
	0x38, 0x95, 0x06, 0xc7, 0xa2, 0x2c, 0x15, 0x6a, 0xed, 0x4b, 0x3d, 0x88, 0x66, 0x3f, 0x03, 0xe8,
	0x9d, 0xab, 0xda, 0xde, 0x41, 0x89, 0x9b, 0xee, 0x0e, 0x4a, 0xdc, 0xd8, 0xc7, 0x41, 0x6a, 0x14,
	0xb2, 0xf6, 0xdc, 0xa5, 0x6f, 0xf7, 0xeb, 0xb2, 0xad, 0x6b, 0x5a, 0x8a, 0x84, 0x93, 0x6d, 0xf1,
	0x95, 0xd4, 0xa6, 0x11, 0x53, 0xf4, 0xc3, 0x5e, 0xfa, 0x16, 0x3f, 0x93, 0xca, 0xf8, 0x31, 0x93,
	0x4d, 0xf5, 0x85, 0xa9, 0x08, 0x1f, 0xfa, 0xfa, 0xde, 0xb7, 0x8b, 0xa1, 0x51, 0xa8, 0xa2, 0xa2,
	0x59, 0x26, 0xdc, 0x7b, 0xb6, 0x4e, 0x25, 0x74, 0x95, 0xc6, 0xae, 0x8e, 0xb5, 0xb3, 0x72, 0xad,
	0x67, 0x62, 0x4b, 0xbb, 0xf9, 0xf9, 0xa6, 0xbc, 0xc7, 0x9e, 0x03, 0xd8, 0x4f, 0x69, 0x2c, 0xae,
	0xba, 0x17, 0x9b, 0xf0, 0xc4, 0x46, 0x3e, 0xd9, 0xc0, 0x85, 0xfb, 0xc1, 0x0f, 0xfe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x09, 0xc6, 0x4b, 0x8b, 0xe0, 0x05, 0x00, 0x00,
}
