// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/errorv2.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Timestamp            int64              `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string             `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	TransactionId        string             `protobuf:"bytes,3,opt,name=transaction_id,proto3" json:"transaction_id,omitempty"`
	TraceId              string             `protobuf:"bytes,4,opt,name=trace_id,proto3" json:"trace_id,omitempty"`
	ParentId             string             `protobuf:"bytes,5,opt,name=parent_id,proto3" json:"parent_id,omitempty"`
	Transaction          *Error_Transaction `protobuf:"bytes,6,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Context              *Context           `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`
	Culprit              string             `protobuf:"bytes,8,opt,name=culprit,proto3" json:"culprit,omitempty"`
	Exception            *Error_Exception   `protobuf:"bytes,9,opt,name=exception,proto3" json:"exception,omitempty"`
	Log                  *Error_Log         `protobuf:"bytes,10,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc214fbb37b13b78, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Error) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Error) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *Error) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Error) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Error) GetTransaction() *Error_Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *Error) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Error) GetCulprit() string {
	if m != nil {
		return m.Culprit
	}
	return ""
}

func (m *Error) GetException() *Error_Exception {
	if m != nil {
		return m.Exception
	}
	return nil
}

func (m *Error) GetLog() *Error_Log {
	if m != nil {
		return m.Log
	}
	return nil
}

type Error_Exception struct {
	Code                 string            `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Module               string            `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	Attributes           map[string]string `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Stacktrace           []*StackTrace     `protobuf:"bytes,5,rep,name=stacktrace,proto3" json:"stacktrace,omitempty"`
	Handled              bool              `protobuf:"varint,6,opt,name=handled,proto3" json:"handled,omitempty"`
	Type                 string            `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Error_Exception) Reset()         { *m = Error_Exception{} }
func (m *Error_Exception) String() string { return proto.CompactTextString(m) }
func (*Error_Exception) ProtoMessage()    {}
func (*Error_Exception) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc214fbb37b13b78, []int{0, 0}
}

func (m *Error_Exception) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_Exception.Unmarshal(m, b)
}
func (m *Error_Exception) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_Exception.Marshal(b, m, deterministic)
}
func (m *Error_Exception) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_Exception.Merge(m, src)
}
func (m *Error_Exception) XXX_Size() int {
	return xxx_messageInfo_Error_Exception.Size(m)
}
func (m *Error_Exception) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_Exception.DiscardUnknown(m)
}

var xxx_messageInfo_Error_Exception proto.InternalMessageInfo

func (m *Error_Exception) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error_Exception) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error_Exception) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *Error_Exception) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Error_Exception) GetStacktrace() []*StackTrace {
	if m != nil {
		return m.Stacktrace
	}
	return nil
}

func (m *Error_Exception) GetHandled() bool {
	if m != nil {
		return m.Handled
	}
	return false
}

func (m *Error_Exception) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Error_Log struct {
	Level                string        `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	LoggerName           string        `protobuf:"bytes,2,opt,name=logger_name,proto3" json:"logger_name,omitempty"`
	Message              string        `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ParamMessage         string        `protobuf:"bytes,4,opt,name=param_message,proto3" json:"param_message,omitempty"`
	Stacktrace           []*StackTrace `protobuf:"bytes,5,rep,name=stacktrace,proto3" json:"stacktrace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Error_Log) Reset()         { *m = Error_Log{} }
func (m *Error_Log) String() string { return proto.CompactTextString(m) }
func (*Error_Log) ProtoMessage()    {}
func (*Error_Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc214fbb37b13b78, []int{0, 1}
}

func (m *Error_Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_Log.Unmarshal(m, b)
}
func (m *Error_Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_Log.Marshal(b, m, deterministic)
}
func (m *Error_Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_Log.Merge(m, src)
}
func (m *Error_Log) XXX_Size() int {
	return xxx_messageInfo_Error_Log.Size(m)
}
func (m *Error_Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Error_Log proto.InternalMessageInfo

func (m *Error_Log) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Error_Log) GetLoggerName() string {
	if m != nil {
		return m.LoggerName
	}
	return ""
}

func (m *Error_Log) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error_Log) GetParamMessage() string {
	if m != nil {
		return m.ParamMessage
	}
	return ""
}

func (m *Error_Log) GetStacktrace() []*StackTrace {
	if m != nil {
		return m.Stacktrace
	}
	return nil
}

type Error_Transaction struct {
	Sampled              bool     `protobuf:"varint,1,opt,name=sampled,proto3" json:"sampled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error_Transaction) Reset()         { *m = Error_Transaction{} }
func (m *Error_Transaction) String() string { return proto.CompactTextString(m) }
func (*Error_Transaction) ProtoMessage()    {}
func (*Error_Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc214fbb37b13b78, []int{0, 2}
}

func (m *Error_Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_Transaction.Unmarshal(m, b)
}
func (m *Error_Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_Transaction.Marshal(b, m, deterministic)
}
func (m *Error_Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_Transaction.Merge(m, src)
}
func (m *Error_Transaction) XXX_Size() int {
	return xxx_messageInfo_Error_Transaction.Size(m)
}
func (m *Error_Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Error_Transaction proto.InternalMessageInfo

func (m *Error_Transaction) GetSampled() bool {
	if m != nil {
		return m.Sampled
	}
	return false
}

func init() {
	proto.RegisterType((*Error)(nil), "protos.Error")
	proto.RegisterType((*Error_Exception)(nil), "protos.Error.Exception")
	proto.RegisterMapType((map[string]string)(nil), "protos.Error.Exception.AttributesEntry")
	proto.RegisterType((*Error_Log)(nil), "protos.Error.Log")
	proto.RegisterType((*Error_Transaction)(nil), "protos.Error.Transaction")
}

func init() { proto.RegisterFile("protos/errorv2.proto", fileDescriptor_bc214fbb37b13b78) }

var fileDescriptor_bc214fbb37b13b78 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x55, 0x92, 0xfd, 0xca, 0x44, 0xb4, 0x30, 0xaa, 0xa8, 0x89, 0x38, 0x44, 0x80, 0xe8, 0x72,
	0x59, 0xa4, 0x45, 0x48, 0x08, 0xc4, 0x01, 0xa1, 0x15, 0x97, 0x9e, 0x4c, 0xef, 0x2b, 0x37, 0xb1,
	0x42, 0xd4, 0x24, 0x8e, 0x6c, 0xef, 0xaa, 0xfb, 0x2f, 0xf8, 0x2b, 0x9c, 0xf9, 0x73, 0xc8, 0x76,
	0xbc, 0xc9, 0x56, 0xe2, 0xd2, 0x9b, 0xdf, 0xbc, 0x79, 0x33, 0x2f, 0xcf, 0x0e, 0x5c, 0x74, 0x52,
	0x68, 0xa1, 0xde, 0x73, 0x29, 0x85, 0xdc, 0xaf, 0x57, 0x16, 0xe2, 0xcc, 0x55, 0x53, 0xcf, 0xe6,
	0xa2, 0xd5, 0xfc, 0x5e, 0x3b, 0x36, 0xbd, 0xec, 0xab, 0x4a, 0xb3, 0xfc, 0x4e, 0x4b, 0x96, 0x73,
	0x47, 0xbc, 0xfa, 0x3d, 0x87, 0xe9, 0xc6, 0x0c, 0xc2, 0x97, 0x10, 0xeb, 0xaa, 0xe1, 0x4a, 0xb3,
	0xa6, 0x23, 0x41, 0x16, 0x2c, 0x23, 0x3a, 0x14, 0xf0, 0x0c, 0xc2, 0xaa, 0x20, 0x61, 0x16, 0x2c,
	0x63, 0x1a, 0x56, 0x05, 0xbe, 0x85, 0x33, 0x2d, 0x59, 0xab, 0x58, 0xae, 0x2b, 0xd1, 0x6e, 0xab,
	0x82, 0x44, 0x96, 0x7b, 0x50, 0xc5, 0x14, 0x16, 0x76, 0x9d, 0xe9, 0x98, 0xd8, 0x8e, 0x23, 0x36,
	0x1b, 0x3b, 0x26, 0x79, 0xab, 0x0d, 0x39, 0xb5, 0xe4, 0x50, 0xc0, 0x2f, 0x90, 0x8c, 0x66, 0x91,
	0x59, 0x16, 0x2c, 0x93, 0xf5, 0x0b, 0x67, 0x5b, 0xad, 0xac, 0xe7, 0xd5, 0xcd, 0xd0, 0x40, 0xc7,
	0xdd, 0xf8, 0x0e, 0xe6, 0x7d, 0x00, 0x64, 0x6e, 0x85, 0xe7, 0x5e, 0xf8, 0xdd, 0x95, 0xa9, 0xe7,
	0x91, 0xc0, 0x3c, 0xdf, 0xd5, 0x9d, 0xac, 0x34, 0x59, 0x58, 0x0f, 0x1e, 0xe2, 0x47, 0x88, 0xf9,
	0x7d, 0xce, 0x3b, 0xbb, 0x3f, 0xb6, 0x63, 0x2e, 0x4f, 0xf7, 0x6f, 0x3c, 0x4d, 0x87, 0x4e, 0x7c,
	0x0d, 0x51, 0x2d, 0x4a, 0x02, 0x56, 0xf0, 0xec, 0x54, 0x70, 0x2d, 0x4a, 0x6a, 0xd8, 0xf4, 0x6f,
	0x08, 0xf1, 0x51, 0x8d, 0x08, 0x93, 0x5c, 0x14, 0xdc, 0xc6, 0x1e, 0x53, 0x7b, 0x36, 0xbe, 0x1a,
	0xae, 0x14, 0x2b, 0x79, 0x1f, 0xbb, 0x87, 0xf8, 0x1c, 0x66, 0x8d, 0x28, 0x76, 0x35, 0xef, 0x33,
	0xef, 0x11, 0xfe, 0x00, 0x60, 0x5a, 0xcb, 0xea, 0x76, 0xa7, 0xb9, 0x22, 0x93, 0x2c, 0x5a, 0x26,
	0xeb, 0xab, 0xff, 0x18, 0x5e, 0x7d, 0x3b, 0x76, 0x6e, 0x5a, 0x2d, 0x0f, 0x74, 0x24, 0xc5, 0x35,
	0xc0, 0xf0, 0x50, 0xc8, 0xd4, 0x0e, 0x42, 0x3f, 0xe8, 0xa7, 0x61, 0x6e, 0x0c, 0x43, 0x47, 0x5d,
	0xc6, 0xee, 0x2f, 0xd6, 0x16, 0x35, 0x2f, 0xec, 0x55, 0x2d, 0xa8, 0x87, 0xe6, 0xe3, 0xf4, 0xa1,
	0xe3, 0xf6, 0x22, 0x62, 0x6a, 0xcf, 0xe9, 0x57, 0x38, 0x7f, 0x60, 0x00, 0x9f, 0x42, 0x74, 0xc7,
	0x0f, 0x7d, 0x04, 0xe6, 0x88, 0x17, 0x30, 0xdd, 0xb3, 0x7a, 0xe7, 0xbf, 0xdf, 0x81, 0xcf, 0xe1,
	0xa7, 0x20, 0xfd, 0x13, 0x40, 0x74, 0x2d, 0x4a, 0xd3, 0x51, 0xf3, 0x3d, 0xaf, 0x7b, 0x95, 0x03,
	0x98, 0x41, 0x52, 0x8b, 0xb2, 0xe4, 0x72, 0xdb, 0xb2, 0xc6, 0xab, 0xc7, 0xa5, 0x71, 0xb6, 0xd1,
	0x69, 0xb6, 0x6f, 0xe0, 0x49, 0xc7, 0x24, 0x6b, 0xb6, 0x9e, 0x77, 0x8f, 0xf6, 0xb4, 0xf8, 0x98,
	0x80, 0xd2, 0x2b, 0x48, 0x46, 0xcf, 0xd5, 0x58, 0x50, 0xac, 0xe9, 0x4c, 0x5e, 0x81, 0xcb, 0xab,
	0x87, 0xb7, 0xee, 0x4f, 0xfe, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xce, 0x88, 0x61, 0x0b, 0xe8,
	0x03, 0x00, 0x00,
}
