// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/service.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Service struct {
	Agent                *Service_Agent     `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Framework            *Service_Framework `protobuf:"bytes,2,opt,name=framework,proto3" json:"framework,omitempty"`
	Language             *Service_Language  `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Name                 string             `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Environment          string             `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	Runtime              *Service_Runtime   `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Version              string             `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c8ddc7a57d07169, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetAgent() *Service_Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *Service) GetFramework() *Service_Framework {
	if m != nil {
		return m.Framework
	}
	return nil
}

func (m *Service) GetLanguage() *Service_Language {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *Service) GetRuntime() *Service_Runtime {
	if m != nil {
		return m.Runtime
	}
	return nil
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Service_Framework struct {
	// Name and version of the web framework used
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service_Framework) Reset()         { *m = Service_Framework{} }
func (m *Service_Framework) String() string { return proto.CompactTextString(m) }
func (*Service_Framework) ProtoMessage()    {}
func (*Service_Framework) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c8ddc7a57d07169, []int{0, 0}
}

func (m *Service_Framework) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service_Framework.Unmarshal(m, b)
}
func (m *Service_Framework) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service_Framework.Marshal(b, m, deterministic)
}
func (m *Service_Framework) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service_Framework.Merge(m, src)
}
func (m *Service_Framework) XXX_Size() int {
	return xxx_messageInfo_Service_Framework.Size(m)
}
func (m *Service_Framework) XXX_DiscardUnknown() {
	xxx_messageInfo_Service_Framework.DiscardUnknown(m)
}

var xxx_messageInfo_Service_Framework proto.InternalMessageInfo

func (m *Service_Framework) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service_Framework) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Service_Language struct {
	// Name and version of the programming language used
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service_Language) Reset()         { *m = Service_Language{} }
func (m *Service_Language) String() string { return proto.CompactTextString(m) }
func (*Service_Language) ProtoMessage()    {}
func (*Service_Language) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c8ddc7a57d07169, []int{0, 1}
}

func (m *Service_Language) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service_Language.Unmarshal(m, b)
}
func (m *Service_Language) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service_Language.Marshal(b, m, deterministic)
}
func (m *Service_Language) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service_Language.Merge(m, src)
}
func (m *Service_Language) XXX_Size() int {
	return xxx_messageInfo_Service_Language.Size(m)
}
func (m *Service_Language) XXX_DiscardUnknown() {
	xxx_messageInfo_Service_Language.DiscardUnknown(m)
}

var xxx_messageInfo_Service_Language proto.InternalMessageInfo

func (m *Service_Language) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service_Language) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Service_Agent struct {
	// Name and version of the Elastic APM agent
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service_Agent) Reset()         { *m = Service_Agent{} }
func (m *Service_Agent) String() string { return proto.CompactTextString(m) }
func (*Service_Agent) ProtoMessage()    {}
func (*Service_Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c8ddc7a57d07169, []int{0, 2}
}

func (m *Service_Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service_Agent.Unmarshal(m, b)
}
func (m *Service_Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service_Agent.Marshal(b, m, deterministic)
}
func (m *Service_Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service_Agent.Merge(m, src)
}
func (m *Service_Agent) XXX_Size() int {
	return xxx_messageInfo_Service_Agent.Size(m)
}
func (m *Service_Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Service_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Service_Agent proto.InternalMessageInfo

func (m *Service_Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service_Agent) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Service_Runtime struct {
	// Name and version of the language runtime running this service
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service_Runtime) Reset()         { *m = Service_Runtime{} }
func (m *Service_Runtime) String() string { return proto.CompactTextString(m) }
func (*Service_Runtime) ProtoMessage()    {}
func (*Service_Runtime) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c8ddc7a57d07169, []int{0, 3}
}

func (m *Service_Runtime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service_Runtime.Unmarshal(m, b)
}
func (m *Service_Runtime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service_Runtime.Marshal(b, m, deterministic)
}
func (m *Service_Runtime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service_Runtime.Merge(m, src)
}
func (m *Service_Runtime) XXX_Size() int {
	return xxx_messageInfo_Service_Runtime.Size(m)
}
func (m *Service_Runtime) XXX_DiscardUnknown() {
	xxx_messageInfo_Service_Runtime.DiscardUnknown(m)
}

var xxx_messageInfo_Service_Runtime proto.InternalMessageInfo

func (m *Service_Runtime) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service_Runtime) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*Service)(nil), "protos.Service")
	proto.RegisterType((*Service_Framework)(nil), "protos.Service.Framework")
	proto.RegisterType((*Service_Language)(nil), "protos.Service.Language")
	proto.RegisterType((*Service_Agent)(nil), "protos.Service.Agent")
	proto.RegisterType((*Service_Runtime)(nil), "protos.Service.Runtime")
}

func init() { proto.RegisterFile("protos/service.proto", fileDescriptor_4c8ddc7a57d07169) }

var fileDescriptor_4c8ddc7a57d07169 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x95, 0x92, 0xd4, 0xcd, 0x75, 0x3b, 0x81, 0x38, 0x98, 0x22, 0xa6, 0x4a, 0x48, 0x41,
	0xfc, 0x53, 0x61, 0x64, 0x61, 0xea, 0x64, 0x9e, 0xc0, 0xa0, 0x23, 0x8a, 0x20, 0x36, 0x72, 0xd2,
	0xf0, 0x14, 0xbc, 0x33, 0xea, 0x39, 0x09, 0x21, 0x53, 0xbb, 0xf9, 0xee, 0xfb, 0x7e, 0xbe, 0xfb,
	0x2c, 0xc3, 0xf1, 0x97, 0x77, 0x8d, 0xab, 0xaf, 0x6a, 0xf6, 0x6d, 0xf9, 0xc6, 0xb9, 0x94, 0x38,
	0x0f, 0xdd, 0x8b, 0x9f, 0x18, 0xd4, 0x4b, 0x50, 0xf0, 0x12, 0x12, 0x53, 0xb0, 0x6d, 0x28, 0xca,
	0xa2, 0xd5, 0xf2, 0xe6, 0x24, 0x58, 0xeb, 0xbc, 0xd3, 0xf3, 0xa7, 0x9d, 0xa8, 0x83, 0x07, 0xd7,
	0x90, 0xbe, 0x7b, 0x53, 0xf1, 0xb7, 0xf3, 0x1f, 0x34, 0x13, 0xe0, 0x6c, 0x0a, 0x3c, 0xf7, 0x06,
	0xfd, 0xe7, 0xc5, 0x3b, 0x58, 0x7c, 0x1a, 0x5b, 0x6c, 0x4d, 0xc1, 0x74, 0x24, 0x1c, 0x4d, 0xb9,
	0x4d, 0xa7, 0xeb, 0xc1, 0x89, 0x08, 0xb1, 0x35, 0x15, 0x53, 0x9c, 0x45, 0xab, 0x54, 0xcb, 0x19,
	0x33, 0x58, 0xb2, 0x6d, 0x4b, 0xef, 0x6c, 0xb5, 0xdb, 0x3a, 0x11, 0x69, 0xdc, 0xc2, 0x6b, 0x50,
	0x7e, 0x6b, 0x9b, 0xb2, 0x62, 0x9a, 0xcb, 0xa8, 0xd3, 0xe9, 0x28, 0x1d, 0x64, 0xdd, 0xfb, 0x90,
	0x40, 0xb5, 0xec, 0xeb, 0xd2, 0x59, 0x52, 0x72, 0x61, 0x5f, 0x9e, 0x3f, 0x42, 0x3a, 0x04, 0x1a,
	0xf6, 0x89, 0x46, 0xfb, 0x8c, 0xd0, 0xd9, 0x7f, 0xf4, 0x01, 0x16, 0x9b, 0x69, 0x92, 0xfd, 0xc8,
	0x7b, 0x48, 0xe4, 0xd9, 0x0f, 0xc4, 0xd6, 0xa0, 0xba, 0x64, 0x87, 0x81, 0xaf, 0xe1, 0x5f, 0xdc,
	0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xed, 0x0a, 0x19, 0x70, 0x36, 0x02, 0x00, 0x00,
}
