// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/stacktrace.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StackTrace struct {
	AbsPath              string            `protobuf:"bytes,1,opt,name=abs_path,proto3" json:"abs_path,omitempty"`
	Colno                int32             `protobuf:"varint,2,opt,name=colno,proto3" json:"colno,omitempty"`
	ContextLine          string            `protobuf:"bytes,3,opt,name=context_line,proto3" json:"context_line,omitempty"`
	Filename             string            `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	Function             string            `protobuf:"bytes,5,opt,name=function,proto3" json:"function,omitempty"`
	LibraryFrame         bool              `protobuf:"varint,6,opt,name=library_frame,proto3" json:"library_frame,omitempty"`
	Lineno               int32             `protobuf:"varint,7,opt,name=lineno,proto3" json:"lineno,omitempty"`
	Module               string            `protobuf:"bytes,8,opt,name=module,proto3" json:"module,omitempty"`
	PostContext          []string          `protobuf:"bytes,9,rep,name=post_context,proto3" json:"post_context,omitempty"`
	PreContext           []string          `protobuf:"bytes,10,rep,name=pre_context,proto3" json:"pre_context,omitempty"`
	Vars                 map[string]string `protobuf:"bytes,11,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StackTrace) Reset()         { *m = StackTrace{} }
func (m *StackTrace) String() string { return proto.CompactTextString(m) }
func (*StackTrace) ProtoMessage()    {}
func (*StackTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf589c06602ac3f1, []int{0}
}

func (m *StackTrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackTrace.Unmarshal(m, b)
}
func (m *StackTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackTrace.Marshal(b, m, deterministic)
}
func (m *StackTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackTrace.Merge(m, src)
}
func (m *StackTrace) XXX_Size() int {
	return xxx_messageInfo_StackTrace.Size(m)
}
func (m *StackTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_StackTrace.DiscardUnknown(m)
}

var xxx_messageInfo_StackTrace proto.InternalMessageInfo

func (m *StackTrace) GetAbsPath() string {
	if m != nil {
		return m.AbsPath
	}
	return ""
}

func (m *StackTrace) GetColno() int32 {
	if m != nil {
		return m.Colno
	}
	return 0
}

func (m *StackTrace) GetContextLine() string {
	if m != nil {
		return m.ContextLine
	}
	return ""
}

func (m *StackTrace) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *StackTrace) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *StackTrace) GetLibraryFrame() bool {
	if m != nil {
		return m.LibraryFrame
	}
	return false
}

func (m *StackTrace) GetLineno() int32 {
	if m != nil {
		return m.Lineno
	}
	return 0
}

func (m *StackTrace) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *StackTrace) GetPostContext() []string {
	if m != nil {
		return m.PostContext
	}
	return nil
}

func (m *StackTrace) GetPreContext() []string {
	if m != nil {
		return m.PreContext
	}
	return nil
}

func (m *StackTrace) GetVars() map[string]string {
	if m != nil {
		return m.Vars
	}
	return nil
}

func init() {
	proto.RegisterType((*StackTrace)(nil), "protos.StackTrace")
	proto.RegisterMapType((map[string]string)(nil), "protos.StackTrace.VarsEntry")
}

func init() { proto.RegisterFile("protos/stacktrace.proto", fileDescriptor_cf589c06602ac3f1) }

var fileDescriptor_cf589c06602ac3f1 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcd, 0x4e, 0x84, 0x30,
	0x14, 0x85, 0xc3, 0x30, 0x20, 0x5c, 0x34, 0x31, 0x8d, 0xd1, 0x66, 0xe2, 0xa2, 0x99, 0xb8, 0x60,
	0x85, 0x46, 0x17, 0x1a, 0xf7, 0xbe, 0x00, 0x1a, 0xb7, 0xa4, 0x60, 0x27, 0x92, 0xe9, 0xb4, 0xa4,
	0x2d, 0x13, 0x79, 0x1c, 0xdf, 0xd4, 0xf4, 0x47, 0x66, 0x66, 0xc7, 0xf9, 0xce, 0xbd, 0x97, 0x93,
	0x53, 0xb8, 0x19, 0x94, 0x34, 0x52, 0xdf, 0x6b, 0x43, 0xbb, 0xad, 0x51, 0xb4, 0x63, 0x95, 0x23,
	0x28, 0xf5, 0xc6, 0xfa, 0x37, 0x06, 0x78, 0xb7, 0xe6, 0x87, 0x35, 0xd1, 0x0a, 0x32, 0xda, 0xea,
	0x66, 0xa0, 0xe6, 0x1b, 0x47, 0x24, 0x2a, 0xf3, 0x7a, 0xd6, 0xe8, 0x0a, 0x92, 0x4e, 0x72, 0x21,
	0xf1, 0x82, 0x44, 0x65, 0x52, 0x7b, 0x81, 0xd6, 0x70, 0xde, 0x49, 0x61, 0xd8, 0x8f, 0x69, 0x78,
	0x2f, 0x18, 0x8e, 0xdd, 0xd6, 0x09, 0xb3, 0x57, 0x37, 0x3d, 0x67, 0x82, 0xee, 0x18, 0x5e, 0xfa,
	0xab, 0xff, 0xda, 0x79, 0xa3, 0xe8, 0x4c, 0x2f, 0x05, 0x4e, 0x82, 0x17, 0x34, 0xba, 0x83, 0x0b,
	0xde, 0xb7, 0x8a, 0xaa, 0xa9, 0xd9, 0x28, 0xbb, 0x9c, 0x92, 0xa8, 0xcc, 0xea, 0x53, 0x88, 0xae,
	0x21, 0xb5, 0x7f, 0x11, 0x12, 0x9f, 0xb9, 0x60, 0x41, 0x59, 0xbe, 0x93, 0x5f, 0x23, 0x67, 0x38,
	0x73, 0x77, 0x83, 0xb2, 0x89, 0x07, 0xa9, 0x4d, 0x13, 0x22, 0xe2, 0x9c, 0xc4, 0x36, 0xf1, 0x31,
	0x43, 0x04, 0x8a, 0x41, 0xb1, 0x79, 0x04, 0xdc, 0xc8, 0x31, 0x42, 0x0f, 0xb0, 0xdc, 0x53, 0xa5,
	0x71, 0x41, 0xe2, 0xb2, 0x78, 0xbc, 0xf5, 0xb5, 0xea, 0xea, 0xd0, 0x65, 0xf5, 0x49, 0x95, 0x7e,
	0x13, 0x46, 0x4d, 0xb5, 0x9b, 0x5c, 0x3d, 0x43, 0x3e, 0x23, 0x74, 0x09, 0xf1, 0x96, 0x4d, 0xa1,
	0x63, 0xfb, 0x69, 0xeb, 0xdd, 0x53, 0x3e, 0x32, 0x57, 0x6f, 0x5e, 0x7b, 0xf1, 0xba, 0x78, 0x89,
	0x5a, 0xff, 0x56, 0x4f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x40, 0x5f, 0x26, 0x3d, 0xcd, 0x01,
	0x00, 0x00,
}
