// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/system.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type System struct {
	Architecture         string             `protobuf:"bytes,1,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Hostname             string             `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Platform             string             `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Container            *System_Container  `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	Kubernetes           *System_Kubernetes `protobuf:"bytes,5,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *System) Reset()         { *m = System{} }
func (m *System) String() string { return proto.CompactTextString(m) }
func (*System) ProtoMessage()    {}
func (*System) Descriptor() ([]byte, []int) {
	return fileDescriptor_d755300ce4de909a, []int{0}
}

func (m *System) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_System.Unmarshal(m, b)
}
func (m *System) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_System.Marshal(b, m, deterministic)
}
func (m *System) XXX_Merge(src proto.Message) {
	xxx_messageInfo_System.Merge(m, src)
}
func (m *System) XXX_Size() int {
	return xxx_messageInfo_System.Size(m)
}
func (m *System) XXX_DiscardUnknown() {
	xxx_messageInfo_System.DiscardUnknown(m)
}

var xxx_messageInfo_System proto.InternalMessageInfo

func (m *System) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *System) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *System) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *System) GetContainer() *System_Container {
	if m != nil {
		return m.Container
	}
	return nil
}

func (m *System) GetKubernetes() *System_Kubernetes {
	if m != nil {
		return m.Kubernetes
	}
	return nil
}

type System_Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *System_Container) Reset()         { *m = System_Container{} }
func (m *System_Container) String() string { return proto.CompactTextString(m) }
func (*System_Container) ProtoMessage()    {}
func (*System_Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_d755300ce4de909a, []int{0, 0}
}

func (m *System_Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_System_Container.Unmarshal(m, b)
}
func (m *System_Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_System_Container.Marshal(b, m, deterministic)
}
func (m *System_Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_System_Container.Merge(m, src)
}
func (m *System_Container) XXX_Size() int {
	return xxx_messageInfo_System_Container.Size(m)
}
func (m *System_Container) XXX_DiscardUnknown() {
	xxx_messageInfo_System_Container.DiscardUnknown(m)
}

var xxx_messageInfo_System_Container proto.InternalMessageInfo

func (m *System_Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type System_Kubernetes struct {
	Namespace            string                  `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod                  *System_Kubernetes_Pod  `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Node                 *System_Kubernetes_Node `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *System_Kubernetes) Reset()         { *m = System_Kubernetes{} }
func (m *System_Kubernetes) String() string { return proto.CompactTextString(m) }
func (*System_Kubernetes) ProtoMessage()    {}
func (*System_Kubernetes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d755300ce4de909a, []int{0, 1}
}

func (m *System_Kubernetes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_System_Kubernetes.Unmarshal(m, b)
}
func (m *System_Kubernetes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_System_Kubernetes.Marshal(b, m, deterministic)
}
func (m *System_Kubernetes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_System_Kubernetes.Merge(m, src)
}
func (m *System_Kubernetes) XXX_Size() int {
	return xxx_messageInfo_System_Kubernetes.Size(m)
}
func (m *System_Kubernetes) XXX_DiscardUnknown() {
	xxx_messageInfo_System_Kubernetes.DiscardUnknown(m)
}

var xxx_messageInfo_System_Kubernetes proto.InternalMessageInfo

func (m *System_Kubernetes) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *System_Kubernetes) GetPod() *System_Kubernetes_Pod {
	if m != nil {
		return m.Pod
	}
	return nil
}

func (m *System_Kubernetes) GetNode() *System_Kubernetes_Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type System_Kubernetes_Pod struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *System_Kubernetes_Pod) Reset()         { *m = System_Kubernetes_Pod{} }
func (m *System_Kubernetes_Pod) String() string { return proto.CompactTextString(m) }
func (*System_Kubernetes_Pod) ProtoMessage()    {}
func (*System_Kubernetes_Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_d755300ce4de909a, []int{0, 1, 0}
}

func (m *System_Kubernetes_Pod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_System_Kubernetes_Pod.Unmarshal(m, b)
}
func (m *System_Kubernetes_Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_System_Kubernetes_Pod.Marshal(b, m, deterministic)
}
func (m *System_Kubernetes_Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_System_Kubernetes_Pod.Merge(m, src)
}
func (m *System_Kubernetes_Pod) XXX_Size() int {
	return xxx_messageInfo_System_Kubernetes_Pod.Size(m)
}
func (m *System_Kubernetes_Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_System_Kubernetes_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_System_Kubernetes_Pod proto.InternalMessageInfo

func (m *System_Kubernetes_Pod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *System_Kubernetes_Pod) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type System_Kubernetes_Node struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *System_Kubernetes_Node) Reset()         { *m = System_Kubernetes_Node{} }
func (m *System_Kubernetes_Node) String() string { return proto.CompactTextString(m) }
func (*System_Kubernetes_Node) ProtoMessage()    {}
func (*System_Kubernetes_Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_d755300ce4de909a, []int{0, 1, 1}
}

func (m *System_Kubernetes_Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_System_Kubernetes_Node.Unmarshal(m, b)
}
func (m *System_Kubernetes_Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_System_Kubernetes_Node.Marshal(b, m, deterministic)
}
func (m *System_Kubernetes_Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_System_Kubernetes_Node.Merge(m, src)
}
func (m *System_Kubernetes_Node) XXX_Size() int {
	return xxx_messageInfo_System_Kubernetes_Node.Size(m)
}
func (m *System_Kubernetes_Node) XXX_DiscardUnknown() {
	xxx_messageInfo_System_Kubernetes_Node.DiscardUnknown(m)
}

var xxx_messageInfo_System_Kubernetes_Node proto.InternalMessageInfo

func (m *System_Kubernetes_Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*System)(nil), "protos.System")
	proto.RegisterType((*System_Container)(nil), "protos.System.Container")
	proto.RegisterType((*System_Kubernetes)(nil), "protos.System.Kubernetes")
	proto.RegisterType((*System_Kubernetes_Pod)(nil), "protos.System.Kubernetes.Pod")
	proto.RegisterType((*System_Kubernetes_Node)(nil), "protos.System.Kubernetes.Node")
}

func init() { proto.RegisterFile("protos/system.proto", fileDescriptor_d755300ce4de909a) }

var fileDescriptor_d755300ce4de909a = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x4d, 0x2c, 0x66, 0x22, 0x22, 0xe3, 0x65, 0x5d, 0x3f, 0x28, 0x3d, 0x15, 0x84, 0x14,
	0x22, 0x08, 0x9e, 0x3d, 0x0a, 0x52, 0xe2, 0x2f, 0x48, 0xb3, 0x23, 0x0d, 0x9a, 0x4c, 0xd8, 0xdd,
	0x1c, 0xfc, 0x95, 0x5e, 0xfd, 0x39, 0x92, 0xdd, 0x26, 0x51, 0xb1, 0xb7, 0x99, 0x79, 0xef, 0xed,
	0xcc, 0x7b, 0x0b, 0xe7, 0xad, 0x66, 0xcb, 0x66, 0x6d, 0x3e, 0x8c, 0xa5, 0x3a, 0x75, 0x1d, 0xce,
	0xfd, 0x70, 0xf9, 0x19, 0xc2, 0xfc, 0xc5, 0x01, 0xb8, 0x84, 0x93, 0x42, 0x97, 0xbb, 0xca, 0x52,
	0x69, 0x3b, 0x4d, 0x22, 0x58, 0x04, 0xab, 0x38, 0xff, 0x35, 0x43, 0x09, 0xc7, 0x3b, 0x36, 0xb6,
	0x29, 0x6a, 0x12, 0x33, 0x87, 0x8f, 0x7d, 0x8f, 0xb5, 0xef, 0x85, 0x7d, 0x65, 0x5d, 0x8b, 0xd0,
	0x63, 0x43, 0x8f, 0xf7, 0x10, 0x97, 0xdc, 0xd8, 0xa2, 0x6a, 0x48, 0x8b, 0x68, 0x11, 0xac, 0x92,
	0x4c, 0xf8, 0x4b, 0x4c, 0xea, 0xd7, 0xa7, 0x8f, 0x03, 0x9e, 0x4f, 0x54, 0x7c, 0x00, 0x78, 0xeb,
	0xb6, 0xa4, 0x1b, 0xb2, 0x64, 0xc4, 0x91, 0x13, 0x5e, 0xfc, 0x11, 0x3e, 0x8d, 0x84, 0xfc, 0x07,
	0x59, 0x5e, 0x42, 0x3c, 0x3e, 0x89, 0xa7, 0x30, 0xab, 0xd4, 0xde, 0xd1, 0xac, 0x52, 0xf2, 0x2b,
	0x00, 0x98, 0x74, 0x78, 0x05, 0x71, 0x6f, 0xc1, 0xb4, 0x45, 0x39, 0xf8, 0x9e, 0x06, 0xb8, 0x86,
	0xb0, 0x65, 0xe5, 0xfc, 0x26, 0xd9, 0xf5, 0xc1, 0xed, 0xe9, 0x86, 0x55, 0xde, 0x33, 0x31, 0x83,
	0xa8, 0x61, 0x45, 0x2e, 0x85, 0x24, 0xbb, 0x39, 0xac, 0x78, 0x66, 0x45, 0xb9, 0xe3, 0xca, 0x5b,
	0x08, 0x37, 0xac, 0x10, 0x21, 0x72, 0xe1, 0xfa, 0x23, 0x5c, 0x8d, 0x67, 0x10, 0x76, 0x95, 0xda,
	0xe7, 0xdd, 0x97, 0x52, 0x42, 0xd4, 0x4b, 0xff, 0x63, 0x6f, 0xfd, 0xcf, 0xde, 0x7d, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x70, 0xe5, 0x6a, 0xce, 0xf7, 0x01, 0x00, 0x00,
}
