// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/transactionv2.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TraceId              string                 `protobuf:"bytes,2,opt,name=trace_id,proto3" json:"trace_id,omitempty"`
	ParentId             string                 `protobuf:"bytes,3,opt,name=parent_id,proto3" json:"parent_id,omitempty"`
	Name                 string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp            int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Duration             float32                `protobuf:"fixed32,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Result               string                 `protobuf:"bytes,8,opt,name=result,proto3" json:"result,omitempty"`
	Sampled              bool                   `protobuf:"varint,9,opt,name=sampled,proto3" json:"sampled,omitempty"`
	Marks                map[string]string      `protobuf:"bytes,10,rep,name=marks,proto3" json:"marks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SpanCount            *Transaction_SpanCount `protobuf:"bytes,11,opt,name=span_count,proto3" json:"span_count,omitempty"`
	Context              *Context               `protobuf:"bytes,12,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ee2f721dd7581df, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Transaction) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Transaction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Transaction) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetDuration() float32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Transaction) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *Transaction) GetSampled() bool {
	if m != nil {
		return m.Sampled
	}
	return false
}

func (m *Transaction) GetMarks() map[string]string {
	if m != nil {
		return m.Marks
	}
	return nil
}

func (m *Transaction) GetSpanCount() *Transaction_SpanCount {
	if m != nil {
		return m.SpanCount
	}
	return nil
}

func (m *Transaction) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

type Transaction_SpanCount struct {
	Started              int32    `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Dropped              int32    `protobuf:"varint,2,opt,name=dropped,proto3" json:"dropped,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_SpanCount) Reset()         { *m = Transaction_SpanCount{} }
func (m *Transaction_SpanCount) String() string { return proto.CompactTextString(m) }
func (*Transaction_SpanCount) ProtoMessage()    {}
func (*Transaction_SpanCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ee2f721dd7581df, []int{0, 1}
}

func (m *Transaction_SpanCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_SpanCount.Unmarshal(m, b)
}
func (m *Transaction_SpanCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_SpanCount.Marshal(b, m, deterministic)
}
func (m *Transaction_SpanCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_SpanCount.Merge(m, src)
}
func (m *Transaction_SpanCount) XXX_Size() int {
	return xxx_messageInfo_Transaction_SpanCount.Size(m)
}
func (m *Transaction_SpanCount) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_SpanCount.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_SpanCount proto.InternalMessageInfo

func (m *Transaction_SpanCount) GetStarted() int32 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *Transaction_SpanCount) GetDropped() int32 {
	if m != nil {
		return m.Dropped
	}
	return 0
}

func init() {
	proto.RegisterType((*Transaction)(nil), "protos.Transaction")
	proto.RegisterMapType((map[string]string)(nil), "protos.Transaction.MarksEntry")
	proto.RegisterType((*Transaction_SpanCount)(nil), "protos.Transaction.SpanCount")
}

func init() { proto.RegisterFile("protos/transactionv2.proto", fileDescriptor_9ee2f721dd7581df) }

var fileDescriptor_9ee2f721dd7581df = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x41, 0x4b, 0xf3, 0x40,
	0x14, 0x24, 0x49, 0xd3, 0x36, 0x2f, 0x1f, 0x9f, 0xb2, 0x14, 0x59, 0x82, 0x4a, 0xf0, 0x14, 0x2f,
	0x15, 0xaa, 0x87, 0x22, 0x88, 0x87, 0xe2, 0xd1, 0xcb, 0xea, 0xbd, 0xac, 0xc9, 0x1e, 0x42, 0x9b,
	0xcd, 0xb2, 0xfb, 0x52, 0xec, 0x1f, 0xf0, 0x77, 0xcb, 0xee, 0x26, 0x4d, 0x0f, 0xde, 0xde, 0xcc,
	0xbc, 0xd9, 0x17, 0x66, 0x02, 0x99, 0xd2, 0x2d, 0xb6, 0xe6, 0x01, 0x35, 0x97, 0x86, 0x97, 0x58,
	0xb7, 0xf2, 0xb0, 0x5a, 0x3a, 0x92, 0x4c, 0xbd, 0x96, 0x2d, 0xfa, 0x9d, 0xb2, 0x95, 0x28, 0xbe,
	0xd1, 0xab, 0x77, 0x3f, 0x13, 0x48, 0x3f, 0x47, 0x17, 0xf9, 0x0f, 0x61, 0x5d, 0xd1, 0x20, 0x0f,
	0x8a, 0x84, 0x85, 0x75, 0x45, 0x32, 0x98, 0xa3, 0xe6, 0xa5, 0xd8, 0xd6, 0x15, 0x0d, 0x1d, 0x7b,
	0xc2, 0xe4, 0x1a, 0x12, 0xc5, 0xb5, 0x90, 0x68, 0xc5, 0xc8, 0x89, 0x23, 0x41, 0x08, 0x4c, 0x24,
	0x6f, 0x04, 0x9d, 0x38, 0xc1, 0xcd, 0x96, 0xc3, 0xa3, 0x12, 0x34, 0xf6, 0x9c, 0x9d, 0xed, 0x2b,
	0x58, 0x37, 0xc2, 0x20, 0x6f, 0x14, 0x9d, 0xe6, 0x41, 0x11, 0xb1, 0x91, 0xb0, 0xf7, 0xab, 0x4e,
	0x73, 0xfb, 0x6d, 0x74, 0x96, 0x07, 0x45, 0xc8, 0x4e, 0x98, 0x5c, 0xc1, 0x54, 0x0b, 0xd3, 0xed,
	0x91, 0xce, 0xdd, 0x7b, 0x3d, 0x22, 0x14, 0x66, 0x86, 0x37, 0x6a, 0x2f, 0x2a, 0x9a, 0xe4, 0x41,
	0x31, 0x67, 0x03, 0x24, 0x4f, 0x10, 0x37, 0x5c, 0xef, 0x0c, 0x85, 0x3c, 0x2a, 0xd2, 0xd5, 0xad,
	0x0f, 0xc1, 0x2c, 0xcf, 0x12, 0x58, 0xbe, 0xdb, 0x85, 0x37, 0x89, 0xfa, 0xc8, 0xfc, 0x32, 0x79,
	0x01, 0x30, 0x8a, 0xcb, 0x6d, 0xd9, 0x76, 0x12, 0x69, 0x9a, 0x07, 0x45, 0xba, 0xba, 0xf9, 0xcb,
	0xfa, 0xa1, 0xb8, 0xdc, 0xd8, 0x25, 0x76, 0x66, 0x20, 0xf7, 0x30, 0xeb, 0x33, 0xa7, 0xff, 0x9c,
	0xf7, 0x62, 0xf0, 0x6e, 0x3c, 0xcd, 0x06, 0x3d, 0x5b, 0x03, 0x8c, 0xe7, 0xc9, 0x25, 0x44, 0x3b,
	0x71, 0xec, 0xcb, 0xb0, 0x23, 0x59, 0x40, 0x7c, 0xe0, 0xfb, 0x4e, 0xf4, 0x55, 0x78, 0xf0, 0x1c,
	0xae, 0x83, 0xec, 0x15, 0x92, 0xd3, 0x75, 0x17, 0x00, 0x72, 0x8d, 0xc2, 0x37, 0x19, 0xb3, 0x01,
	0x5a, 0xa5, 0xd2, 0xad, 0x52, 0xc2, 0xb7, 0x19, 0xb3, 0x01, 0x7e, 0xf9, 0xdf, 0xe4, 0xf1, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x6f, 0xe5, 0x3d, 0x41, 0x4b, 0x02, 0x00, 0x00,
}
